project_id: "468616"
base_path: "planet_states"
branch: "master"
preserve_hierarchy: true
files:
  - source: /localisation/english/*_l_english.yml
    translation: /localisation/%language%/%file_name%_%language%.%file_extension%
    translation_replace:
      _english: ""
    update_option: update_as_unapproved
    languages_mapping:
      language:
        French: "french"
        Spanish: "spanish"
        German: "german"
        Polish: "polish"
        Russian: "russian"
        "Portuguese, Brazilian": "braz_por"
  - source: /localisation/replace/english/*_l_english.yml
    translation: /localisation/replace/%language%/%file_name%_%language%.%file_extension%
    translation_replace:
      _english: ""
    update_option: update_as_unapproved
    languages_mapping:
      language:
        French: "french"
        Spanish: "spanish"
        German: "german"
        Polish: "polish"
        Russian: "russian"
        "Portuguese, Brazilian": "braz_por"
